// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Microservice.Data;

#nullable disable

namespace Product.Microservice.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Product.Microservice.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25d1d4b0-1d0e-459e-9ae7-9b196a0a4e57"),
                            Category = "Category 1",
                            Description = "This is a solid soled shoe",
                            Name = "Solid Shoes",
                            Price = 10.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("afc4468e-2a9d-4e0a-b208-5c71dc21d7ba"),
                            Category = "Category 2",
                            Description = "Black Gucci bag for ladies",
                            Name = "Black Bag",
                            Price = 19.99m,
                            StockQuantity = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
